apiVersion: v1
kind: Service
metadata:
  name: {{ include "caffe.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "caffe.name" . }}
    helm.sh/chart: {{ include "caffe.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.caffe.service.type }}
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: caffe
      {{- if (and (eq .Values.caffe.service.type "NodePort") (not (empty .Values.caffe.service.nodePort)))}}
      nodePort: {{ .Values.caffe.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "caffe.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
